name: "dashboard"
services:
  backend:
    container_name: backend
    build: ./dashboardAPI
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: ./dashboard-ui
    ports:
      - "3000:3000"
 


